### ISSUE TITLE
NOT working

### ISSUE THREAD

**Issue by dadaoros** [Iskuri/gameboy#1]
Don't touch this for gods sake
267718: Pointer at: 0x36e5 with opcode: 0x78
267719: Pointer at: 0x36e6 with opcode: 0xffffffb1
267720: Pointer at: 0x36e7 with opcode: 0x20
267721: Pointer at: 0x36e2 with opcode: 0x7a
267722: Pointer at: 0x36e3 with opcode: 0x22
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 65024
    at gameboy.RAM.writeMem(RAM.java:26)
    at gameboy.Memory.writeMem(Memory.java:108)
    at gameboy.Z80CPU.write8(Z80CPU.java:296)
    at gameboy.Z80CPU.run(Z80CPU.java:576)
    at gameboy.Z80CPU.call(Z80CPU.java:301)
    at gameboy.Z80CPU.run(Z80CPU.java:525)
    at gameboy.Gameboy.main(Gameboy.java:31)

**Comment by Iskuri** [comment]
It's a dead project

**Comment by dadaoros** [comment]
what a pity!
